# Generated by Django 2.2.26 on 2022-08-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="image",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
