# Generated by Django 2.2.26 on 2022-08-04 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_products_seller"),
        ("users", "0003_auto_20220804_0524"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="product",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_product",
                to="home.Products",
            ),
        ),
    ]
